TEST_VALUE:
  name: "cookie"
API-HOST:
  name: 'https://baidu.comm'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  APP_ID: cli_a3da5ea560fad00e
  APP_SECRET: IX0Mt99BS5vO1PvCU3zQgbm3ZQx733Ex
  APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: "fast_gateway_test"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
  username: "xxxx"                   # 数据库链接用户名
  password: "123456"                 # 数据库链接密码
  database: "fast_gateway_test"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
MYSQL_CONFIG1:
  name: "ywtg"
  type: "mysql"
  host: "rm-8vbb80ln9r76mx6t88o.mysql.zhangbei.rds.aliyuncs.com"
  port: 3306
  username: "kangxr"
  password: "kangxiaorui0817$"
  database: "winsdom_community_backups"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true
  charset: 'utf8mb4'
MYSQL_CONFIG:
  name: "wanzi"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "Weining13141314"
  database: "wanzi_test"
  logging: true                     # 数据库打印日志
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true # 是否同步表结构，一般不要开启，避免出现问题
  charset: 'utf8mb4'
REDIS_CONFIG:
  host: "127.0.0.1"  # redis 链接
  port: 6379         # redis 端口=
  auth: "123456"       # redis 连接密码
  db: 0           # redis 数据库
